### ISSUE TITLE
MediaSession::setParams(): Invalid state LinphoneCallStreamsRunning

### ISSUE THREAD

**Issue by MuYiC** [BelledonneCommunications/liblinphone#217] opened 2022-08-31 02:44 UTC
I start a call by this way,first  I setAdudioEnable false
`CallParams params = core.createCallParams(null);
        if (params == null) {
            logger.e(TAG, "startVideoCall: create call params failed.");
            return null;
        }
        params.setVideoEnabled(true);
        params.setAudioEnabled(false);
        call = core.inviteAddressWithParams(address, params);`
a moment later,I need to use audio stream, I setAudioEnable true 
`    CallParams params =core.createCallParams(call);
                        params.setAudioEnabled(true);
                        params.setVideoEnabled(true);
                        call.setParams(params);`

and it show error： MediaSession::setParams(): Invalid state LinphoneCallStreamsRunning
how should i solve this problem?

**Comment by Viish** [comment] 2022-08-31 10:53
Hi @AndreaGianarda, can you take a look at it please?

**Comment by AndreaGianarda** [comment] 2022-09-01 13:17
Hi @MuYiC 

The issue is fixed in the master branch.

Please confirm.

Thanks,

Andrea

**Comment by MuYiC** [comment] 2022-09-02 04:01
Is sdk uploaded to maven repository?

**Comment by Viish** [comment] 2022-09-02 07:15
Hi @MuYiC 

> Is sdk uploaded to maven repository?

Yes, take latest 5.2.0-alpha SDK from maven repository and you'll have the fix.

**Closed by Viish** 2022-09-02 07:15 UTC

**Comment by MuYiC** [comment] 2022-09-02 07:18
I use newest sdk,the issue is fixed. I call 20 times and no crash,thanks!
