### ISSUE TITLE
[Bug]: My app crashes as soon as I answer the call

### ISSUE THREAD

**Issue by jfalexvijay** [BelledonneCommunications/liblinphone#213] opened 2022-07-22 15:13 UTC
### Context

I am trying to create a test video call app for Android. I compiled the linphone lib successfully and integrated. But my test app crashes as soon as I answer the call..

App crashes with the message "Could not load grammar sdp_grammar because the file could not be located."
I have added sdp_grammar file into project.

### General information

- Device: Samsung Galaxy A21
- OS: Android 11
- Version of the SDK: [LinphoneCore version: 5.2.0-alpha]

### Expected behaviour

I wanted to do a simple calling app for Android phone. However, the app crashes as soon as I answer the call.

### To Reproduce

1. Compile linphone library for Android
2. Add it to the Android project (Android Studio).
3. Register as A & B
4. Call B from A and answer the call.

**Comment by Viish** [comment] 2022-11-24 13:05
Duplicate of https://github.com/BelledonneCommunications/liblinphone/issues/204

**Closed by Viish** 2022-11-24 13:05 UTC
Labels: bug
